image:
  file: .gitpod.Dockerfile
  
additionalRepositories:
  - url: https://github.com/AltimateAI/sample_dbt_projects
  - url: https://github.com/ppradnesh/complete-dbt-bootcamp-zero-to-hero

workspaceLocation: complete-dbt-bootcamp-zero-to-hero/project.code-workspace # Relative to /workspace dir

tasks:
  - init: pip install -r requirements.txt
    command: |
      mkdir ~/.dbt; 
      cp ./profiles.yml ~/.dbt/


